version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: processoseletivo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processoseletivo-app
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  local_pgdata:
  minio_data:

networks:
  app-network:
    driver: bridge
